### ISSUE TITLE
Default background not inherited

### ISSUE THREAD

**Issue by aik099** [jkaving/intellij-colors-solarized#101]
For some language elements (at least for PHP language) the background is specified even if it matches default file background. This looks bad since PhpStorm 9.0 release:
![solarizeddark_phpstorm9_issues](https://cloud.githubusercontent.com/assets/1277526/8702446/80d3c220-2b20-11e5-96ad-29a0d34931d1.png)
 
Same problem for Solarized Light.

**Comment by aik099** [comment]
Related to #95.

**Comment by jkaving** [comment]
I just tried downloading the latest PhpStorm 9.0, installed the latest version of `settings.jar` and created a PHP file with parts of your code. I'm running this on OS X 10.10.4.

I don't see the problem, so I'm not sure why it is happening for you:
![screenshot of phpstorm 2015-07-17 09 52 13](https://cloud.githubusercontent.com/assets/725090/8742837/8577fe82-2c69-11e5-9f43-2d47845762d3.png)

Is the version of the color theme that you have in PhpStorm completely unmodified?

**Comment by jkaving** [comment]
Isn't this issue exactly the same as #95?

**Comment by aik099** [comment]
> Isn't this issue exactly the same as #95?

Maybe a sub-set of that issue. Here I'm suggesting to inherit background color when it matches default background color instead of overwriting it.

**Comment by jkaving** [comment]
I have checked the .icls files and none of the PHP language elements have a background color specified.

**Comment by aik099** [comment]
Then it seems how PhpStorm works with theme. I guess it never expected any "php" language elements to appear in the middle of `template language` file part and that's why it looks like this.

Thanks, closing.
