### ISSUE TITLE
Too bright method highlight color (Solarized Dark)

### ISSUE THREAD

**Issue by aik099** [jkaving/intellij-colors-solarized#102]
When you hover mouse over method name in navigation bar (above the editor) it gets highlighted with very bright color making hard to read actual highlighted contents:
![phpstorm_solarizeddark_toobrightmethodhighlight](https://cloud.githubusercontent.com/assets/1277526/8796430/70e60892-2f9d-11e5-9321-04e050033d6f.png)

In comparison same highlight on Default PhpStorm's theme is done like this:
![phpstorm_default_toobrightmethodhighlight](https://cloud.githubusercontent.com/assets/1277526/8796454/99564c7e-2f9d-11e5-958f-255b894f6aef.png)

**Comment by jkaving** [comment]
I see the same problem in PhpStorm 9, but I don't see the highlighting at all in PhpStorm 10.

I found [this issue](https://youtrack.jetbrains.com/issue/WEB-427) which indicates that the behavior has been disabled by default.

And [this StackOverflow answer](http://stackoverflow.com/a/31314139/350692) says that the color cannot be modified - that it uses the caret line color and makes it lighter.

So I don't think we need (or can) to fix this.
