### ISSUE TITLE
Question: am i doing something wrong or looks broken

### ISSUE THREAD

**Issue by blackxored** [jkaving/intellij-colors-solarized#104]
This is after installing with "import settings...":

![](http://d.pr/i/7Lat+)

And this is my Vim:

![](http://d.pr/i/WDdp+)

**Comment by aik099** [comment]
2nd image doesn't show. Can you please reupload.

**Comment by jkaving** [comment]
And, which language is this?

**Comment by ffxsam** [comment]
I can verify, this is not set up right. I'm using WebStorm 10. Note the very dark blue text with certain keywords, which is highly illegible.

![arh23](https://cloud.githubusercontent.com/assets/12532733/9697208/91601aa4-5338-11e5-88d8-ab8f65e3f36e.png)

**Comment by aik099** [comment]
This is not JavaScript, which is supported by IDE, but rather ReactJS syntax. Not sure of IDE supports that.

**Comment by koraktor** [comment]
@aik099 IMHO, even if you open completely unsupported file formats, there shouldn’t be any colors that are not in the color scheme.

**Comment by ffxsam** [comment]
@aik099 WebStorm definitely supports JSX.

I'm in the process of redoing the IntelliJ color scheme. I'll do a PR when it's ready.

**Comment by jkaving** [comment]
@ffxsam That sounds great, looking forward to a pull request.

**Comment by ffxsam** [comment]
It's more work than one would think! :) Just when I think it's done, I run into something I missed. Also, I'm mostly focusing on JavaScript since I don't code in anything else. Maybe I can just point out in the PR that anyone else is welcome to fix other languages if needed, and PR that.

**Comment by jkaving** [comment]
I just downloaded WebStorm 11 and tried it - looks like this now for me:
![screenshot of webstorm 2015-12-22 11-26-05](https://cloud.githubusercontent.com/assets/725090/11953239/e247d5a4-a89e-11e5-8d98-2f2676a8cba7.png)
