### ISSUE TITLE
font size & java colors

### ISSUE THREAD

**Issue by DaRolla** [jkaving/intellij-colors-solarized#105]
hi there,

I am using Android Studio, and after I installed the files I needed to fix the font sized from

    Monospaced  Size 13  Line spacing 1.2 
to 

    Monospaces  Size 12  Line spacing 1.0

which is standard for Darcula

Then comparing to http://ethanschoonover.com/solarized/img/screen-java-dark.png the colors for import e.g. does not match...

Greetings,
DaRolla

**Comment by DaRolla** [comment]
btw. the font size must be applied to Console Font, too

**Comment by jkaving** [comment]
Yes, it is unfortunate that the font settings must be included in the color scheme.
There is a note about it in the readme-file: https://github.com/jkaving/intellij-colors-solarized#note-about-fonts
