### ISSUE TITLE
Cannot import settings automatically into IntelliJ IDEA 15 EAP

### ISSUE THREAD

**Issue by hsinhuang** [jkaving/intellij-colors-solarized#106]
As it is written in `Installation` section of `README.md`, it should be available to import the settings via `File | Import Settings...`, but it doesn't work on IntelliJ IDEA 15 EAP (Build #IU-142.5239). Meanwhile, manual installation is available.

OS: OS X 10.10.5 Yosemite
IntelliJ IDEA: Vesion 15 EAP (Build #IU-142.5239)
Solarized IntelliJ: Commit 5b5a0329486c61c3256fed31356a7a38ff90a5bc

**Comment by trespasserw** [comment]
Seem to work in 143.116 (Linux, but should be no difference).

**Comment by jkaving** [comment]
Yes, it works for me too using 143.116.4 on OS X 10.10.5.

@hsinhuang : which file are you trying to import (it should be `settings.jar`)? What error do you get?

**Comment by hsinhuang** [comment]
@trespasserw @jkaving : work on 143.116 for me too. It seems to be a bug of IntelliJ IDEA.
