### ISSUE TITLE
Wrong method parameter color in PhpStorm 10

### ISSUE THREAD

**Issue by aik099** [jkaving/intellij-colors-solarized#107]
I've just upgraded to PhpStorm 10 and noticed that method parameter color (in declaration and when used) has changed from blue to grey:

PhpStorm 9:
![phpstorm9_yosemite](https://cloud.githubusercontent.com/assets/1277526/10933807/d762a3de-82e3-11e5-99c3-ffd37793c454.png)

PhpStorm 10:
![phpstorm10_yosemite](https://cloud.githubusercontent.com/assets/1277526/10933815/deb5ba54-82e3-11e5-8b0d-aa94b6391adc.png)

Maybe something else is broken, that I haven't noticed yet.

The interesting part is if I inspect theme in settings, the `Language Defaults > Parameter` color is indeed grey. But in the editor it's blue, so I guess parameter is colored in some non standard way (maybe a bug), that was fixed in PhpStorm 10 and such coloring doesn't work.

**Comment by jkaving** [comment]
Yes, I looked at it a bit as well.
It seems as if PhpStorm 9 treats these as variables rather than parameters.

This is a screenshot of the PHP color settings in PhpSorm 9:
![screenshot_of_phpstorm](https://cloud.githubusercontent.com/assets/725090/10937017/76fa4e72-82f0-11e5-9e42-8cbd0703922f.png)
Note that the parameters are gray here.

So I guess if we want to keep the old behavior we could specify that parameters should be blue.

**Comment by aik099** [comment]
> It seems as if PhpStorm 9 treats these as variables rather than parameters.

In actual editor yes, but in color scheme editor it still shows that it's a parameter (when you click on $abc in method declaration) rather than variable.

It's most unlikely that for such a long time PhpStorm was unable to properly detect if variable is defined locally in the method or is in fact a parameter. Maybe in default color scheme they both have same color and therefore nobody noticed coloring bug.

**Comment by aik099** [comment]
Yeah, I've just compared PhpStorm 9 and PhpStorm 10 and:
* PhpStorm 9 thinks, that $abc is both parameter and variable depending on where you click (in method declaration or on variable usage inside)
* PhpStorm 10 thinks, that $abc is parameter no matter where you click.

So yes, setting blue color for method parameters would be great.

**Comment by aik099** [comment]
Maybe we can even change color for method parameters to something other then blue for them to stand out to allow easily spot cases, when method parameters are assigned different values, which is a bad idea. I'm not sure what color would be best for it.

**Comment by aik099** [comment]
@jkaving , any update on color that can be used for method parameters? Do you prefer color used previously (blue, matches method local variables) or maybe another color?

**Comment by jkaving** [comment]
For PHP I don't really have any opinion.

I mainly use Java, and in the color settings for Java we already specify a color (actually a wavy grey underline) for "Reassigned parameter" (the bad idea you mention above). 

I don't see a reason to set a color for parameters in the "Language defaults" settings, but if you want to set it for PHP to get the old behavior back (or perhaps a different color) I think that's ok.

**Comment by aik099** [comment]
Is `wavy grey underline` the color that is used for parameter coloring on the Yosemite screenshot I've attached originally?

If that is so, then you're suggesting not to change anything, because all was fine for Java, but only for PHP there was method parameter coloring issue in PhpStorm <10.

Then OK, you can close this. I'll try to adapt to the new coloring.

**Comment by jkaving** [comment]
It look like this (notice the parameter that is re-assigned):
![screenshot_of_intellij_idea-eap](https://cloud.githubusercontent.com/assets/725090/11088451/a63c3fac-8862-11e5-891d-92edb8bc66fa.png)

Since this feature doesn't seem to exist for PHP, it might actually be a good idea to have a different color for parameters there - feel free to experiment and if you come up with something that looks good I will be glad to merge a pull request.

**Comment by aik099** [comment]
There is `Unused Parameter` inspection in PHP, that detects such use case and it looks like this:
![phpstorm_unusedparameter](https://cloud.githubusercontent.com/assets/1277526/11089159/55f6126c-8870-11e5-8932-af432ea5cb3c.png)

It doesn't however highlight parameter usages inside the method, because technically after assignment this parameter acts just as local variable in that method.

The color change of parameter versus variable in my impression can be helpful to clearly see where the parameters are used. Useful when refactoring as well.

I've tried to choose what color would look better, but only original blue color looks good enough.

**Comment by aik099** [comment]
The magenta color might what I'm after actually. In my previous comment that color is used for "_cacheInvalidator" word coloring (the class property usage).

**Comment by jkaving** [comment]
But then you won't be able to tell the difference between class properties and method parameters?

**Comment by aik099** [comment]
I've tried orange here:
![solarizeddark_phpstorm_orangeparametercolor](https://cloud.githubusercontent.com/assets/1277526/11091128/5638f478-8880-11e5-84d3-f2b7181db92e.png)

Looks good, but does overlap with function color for JavaScript, because they are orange. So I've just set it for PHP parameter color.

**Comment by aik099** [comment]
> But then you won't be able to tell the difference between class properties and method parameters?

Yeah. I've tried orange color because of that problem that I've spotted after posting a screenshot. See above comment.

**Comment by aik099** [comment]
Looked too unusual to me at first, but now seems to be ok. Looks good to you?

**Comment by jkaving** [comment]
If you think it's ok then I have no problems with it (as I said before - I never really use PHP).

**Comment by aik099** [comment]
I've imported `settings.jar` and changed needed color. Then ICLS file that was 109KB before turned out into a file of 105KB size. Lots of changes happened to it.

Maybe PhpStorm removes tags in color scheme that it doesn't understand.
