### ISSUE TITLE
Some issues in IntelliJ 15

### ISSUE THREAD

**Issue by OOPMan** [jkaving/intellij-colors-solarized#108]
I've noticed a couple of issues in IntelliJ 15. Adding some screen-area caps.

![image](https://cloud.githubusercontent.com/assets/248980/10964029/1ede3ec0-83ad-11e5-9a54-b84167e02849.png)

![image](https://cloud.githubusercontent.com/assets/248980/10964058/466c5814-83ad-11e5-98fc-b28763cc43bd.png)

**Comment by OOPMan** [comment]
If I find any more, I'll add.

**Comment by aik099** [comment]
Where is the issue exactly? If you mean, that code block at cursor is highlighted incorrectly, then this isn't color scheme issue it seems.

**Comment by OOPMan** [comment]
Well, in the first image, the background colour highlighting is misbehaving. If I move the cursor to a blank line then the entire line gets highlighted whereas in the image certain areas are not being highlighted.

In the second image, the background/foreground colour combination highlighting the div tag is highly unreadable.

I'm not sure if this is Solarized's fault? I just upgraded from IntelliJ14 to IntelliJ15 and these two things stood out...should I harass JetBrains instead?

**Comment by jkaving** [comment]
Well, the second image definitely shows a problem.

I have been experimenting with using a lighter shade of green (#DDDEB1) for matched braces:
<img width="334" alt="screenshot of intellij idea-eap 2015-11-05 11-02-13" src="https://cloud.githubusercontent.com/assets/725090/10965356/af785c28-83ac-11e5-8668-6bcc908747a1.png">
I think this looks much better, and I think this a case were we should use a non-Solarized color to make the scheme usable.

Unfortunately, the matched brace setting is used for all parentheses and braces - and it is only for XML/HTML tags that it becomes a problem. But I think this looks ok as well:
<img width="178" alt="screenshot of intellij idea-eap 2015-11-05 11-07-48" src="https://cloud.githubusercontent.com/assets/725090/10965485/7943a6c0-83ad-11e5-9be3-0a13c440f90c.png">

What do you think?

**Comment by OOPMan** [comment]
Yes, agreed. I noticed that all of the tag level values are pretty bright but only the green one seems to really cause eye-pain :-)

**Comment by aik099** [comment]
Agreed. Don't forget about Solarized Dark theme as well.
