### ISSUE TITLE
PhpStorm 10, HTML, pair tag highlight not readable

### ISSUE THREAD

**Issue by aik099** [jkaving/intellij-colors-solarized#110]
Since PhpStorm 10 when clicking on HTML tag it's pair tag is highlighted. It looks like this:
![phpstorm10_pairhtmltaghighlight](https://cloud.githubusercontent.com/assets/1277526/11394584/b33047fa-936e-11e5-9e01-ade2838a0989.png)

The result in Solarized Dark (maybe in Solarized Light) theme is completely unreadable. I was looking through all used language elements, but wasn't able to identify which color is that or how it's used.

**Comment by jkaving** [comment]
Isn't this the same problem as #108?
See my comment there about using a different color for matched braces.

**Comment by aik099** [comment]
It is. I've added comment in there. You can close this as duplicate then.
