### ISSUE TITLE
Itellij IDEA 15.0.2  Setting import Fail

### ISSUE THREAD

**Issue by iamyangjy** [jkaving/intellij-colors-solarized#113]
Itellij IDEA 15.0.2  Setting import intellij-color-solarized 
Error
Fail to load plugin descriptor from file intellij-colors-solarized-master.zip

**Comment by jkaving** [comment]
Instead of downloading the project as a zip-file, download the [`settings.jar`](https://github.com/jkaving/intellij-colors-solarized/blob/master/settings.jar?raw=true) file and import that.

**Comment by iamyangjy** [comment]
Still Fail.
My Itellij IDEA version is 15.0.2.
import setting.jar. Eroor:Fail to load plugin descriptor from the file setting.jar

**Comment by jkaving** [comment]
I have no problem importing the downloaded `settings.jar` file using IntelliJ IDEA 15.0.2 on OS X 10.11.2.
Do you get any error message in the IDEA event log (in the lower right of the window)?
![screenshot of intellij idea 2015-12-21 13-08-43](https://cloud.githubusercontent.com/assets/725090/11930475/fb722dd8-a7e3-11e5-814e-79555b7ca72d.png)

**Comment by iamyangjy** [comment]
it's ok now. it's my computuer error . thank you.
