### ISSUE TITLE
Solarized not working correctly with Darcula in Webstorm 11.0.3

### ISSUE THREAD

**Issue by arcseldon** [jkaving/intellij-colors-solarized#115]
Hi, thank you for taking the effort to create this project.

Sorry to tell you, I followed your instructions precisely to install Solarized into Webstorm and the result is a total disaster - unusable the way it looks, with horriblly contrasting colors to the point where some files in the nav bar are near invisible, and the editor is also beyond usable.

Please can you confirm whether you have tested the most recent code base against Webstorm 11.0.3 ?  

At this point, either i have local issues related to my own installation (don't understand how as I took all the defaults), or Solarized is a no-go with Webstorm IDE.

Thank you again for your time, or any pointers as to what might be causing the conflicts.

**Comment by aik099** [comment]
Can you please attach a screenshot and specify OS version.

**Comment by jkaving** [comment]
I just downloaded WebStorm 11.0.3 and installed it on OS X 10.11.2.
It looks ok to me.

Here is the dark version:
<img width="688" alt="screenshot of webstorm 2016-01-23 14-40-52" src="https://cloud.githubusercontent.com/assets/725090/12530434/b6a4b264-c1df-11e5-8510-8e8a798ab985.png">

And here is the light one:
<img width="691" alt="screenshot of webstorm 2016-01-23 14-42-20" src="https://cloud.githubusercontent.com/assets/725090/12530435/be22df16-c1df-11e5-94af-55c5ca258a70.png">

So it should definitely be working in WebStorm.

**Comment by arcseldon** [comment]
@aik099 @jkaving - Using OS X El Capitan, v.10.11.2, Webstorm 11.0.3

ok, sorry guys, i jumped the gun abit on this. have played around with various settings within webstorm preferences. most issues are now resolved, but i still have a couple of problems. (btw, i have converted iterm2 profiles to both solarized light and dark and they look great).

Ok, so here are screenshots, and a couple of examples of issues / questions I have.

Solarized dark is killing the readability in project view of files which reside in the editor (they helpfully get coloured in blue automatically by webstorm with Darcula theme).

![solarized-webstorm11-dark](https://cloud.githubusercontent.com/assets/2599332/12531447/276b97b6-c23e-11e5-8c93-291313235f1f.png)

Solarized light is now looking really good. I just have one question, is there a simple means of getting the project view to also use the same colors as the editor and terminal? (perhaps this is a webstorm question, and not something you guys are concerned with - @jkaving - could you give me screenshots of your webstorm with the project view visible please so i can compare :smile:

![solarized-webstorm11-light](https://cloud.githubusercontent.com/assets/2599332/12531460/917c7e36-c23e-11e5-931f-aed27673fea5.png)


Again, thanks very much for the quick replies, and apologies for exaggerating the issue (which was down to user error and misunderstanding to some extent).

**Comment by aik099** [comment]
The Color Scheme only applies to editor part on the right. The colors in other tool windows (e.g. File Browser, Version Control, Run, etc.) are not controlled by Color Scheme at all.

Probably you have installed "Color Tree" or similar plugin that allows for Color Scheme to be used inside tool windows. That plugin had such problems, when I tried to use it and I've uninstalled it.

**Comment by arcseldon** [comment]
@aik099 thanks for the reply. Nope, not installed color tree or anything else. you can reproduce my problem. Webstorm offers two themes for overall control of the entire IDE themes. Default and Darcula. When I use solarize light, i want to use Default (which is white background by default), and when i use solarize dark, i want to use Darcula. 

But when I do use Darcula theme with the intellij-colors-solarized dark it seems to somehow mess up parts of the Darcula theme too, as per my screenshot. Or at least this is my current understanding.

@jkaving  - please could you try this out?  you are on identical OS and version of Webstorm as me.

Just go into Preferences -> appearance & behaviour -> appearance  and then switch your "Theme" from Default to Darcula.   Now use solarize dark, controlled under Preferences -> Editor -> Colours & Fonts   Scheme.  Next, open a file in the editor and look at it in the project view.  Has it distressed the blue colour as per my screenshot ?

Unfortunately, if so, this problem diminishes the viability of using solarized dark with Intellij family of IDEs.  hope i am wrong here, and there is an easy workaround.

**Comment by aik099** [comment]
> But when I do use Darcula theme with the intellij-colors-solarized dark it seems to somehow mess up parts of the Darcula theme too, as per my screenshot. Or at least this is my current understanding.

You need to use `Solarized Dark (Darkula)` color scheme then not just `Solarized Dark`.

**Comment by arcseldon** [comment]
@aik099 - sorry, you're not making much sense. You previously stated:

>> The Color Scheme only applies to editor part on the right. The colors in other tool windows (e.g. File Browser, Version Control, Run, etc.) are not controlled by Color Scheme at all.

Ok, so why when I use intellij-colors-solarized dark, does it mess up the project view, and tab title as per my screenshot (shown again below). I am not complaining about the Editor window. I am saying it is messing up other parts of the IDE display.

![solarized-webstorm11-dark](https://cloud.githubusercontent.com/assets/2599332/12533465/4ea6c546-c273-11e5-8459-7c196de02c9b.png)

Furthermore, the Darcula scheme for the Editor is different that the intellij-colors-solarized hence why i wish to try the intellij-colors-solarized. It works great for my terminal embedded within Webstorm (dark and light). The problem relates to the intellij part only.

Finally I really didn't understand your final remark:

>> You need to use Solarized Dark (Darkula) color scheme then not just Solarized Dark.

Do you simply mean:

>> You need to use Darcula color scheme and not intellij-colors-solarized dark  ?

Or is there some other combination I don't know about? Because I have no other schemes which combine them available.

**Comment by arcseldon** [comment]
Further information on this.

The Darcula Theme in Webstorm is corrupted, even using the Solarized Light scheme (intellij-colors-solarized). See screenshot below. Furthermore it also affects other panes, such as version control etc.

![update](https://cloud.githubusercontent.com/assets/2599332/12534113/f1e485c6-c28d-11e5-804b-b84dd545e34b.jpg)

**Comment by arcseldon** [comment]
And for your consideration, here is what plain Darcula (out of the box with Webstorm) looks like. No corruption, everything just works.

![darcula](https://cloud.githubusercontent.com/assets/2599332/12534148/f9926238-c28e-11e5-9bd7-d50da7ab99d1.jpg)

**Comment by arcseldon** [comment]
I have raised a [Jetbrains ticket](https://youtrack.jetbrains.com/issue/WEB-19974#) to take a look at this issue too. And in there, I have referenced this issue.
Between the two of  you, please can someone take a look and organise a fix. Thanks very much for providing a great color scheme for Intellij Products, but this issue remains a blocker to adoption for me personally.

**Comment by VernonGrant** [comment]
I just downloaded WebStorm 11.0.3 myself and installed the Solarized theme and everything looks perfect. @arcseldon So I'm thinking that there is definitely an issue with your configuration files somewhere. Did you by any chance upgrade from an older version of WebStorm? (If I was you I'll uninstall WebStorm and make sure that all my configuration files are removed from my home path and do a clean install.)

**Comment by arcseldon** [comment]
@VernonGrant  - Thank you for this valuable feedback. Really appreciate it. .. Can I please make the same request to you that I made earlier to @jkaving 

>> Just go into Preferences -> appearance & behaviour -> appearance and then switch your "Theme" from Default to Darcula. Now use solarize dark, controlled under Preferences -> Editor -> Colours & Fonts Scheme. Next, open a file in the editor and look at it in the project view. Has it distressed the blue colour as per my screenshot ?

Please can you post a screenshot of the result as 'evidence' for me, as it would really help confirm your findings. :smile:

Also, please can you confirm that you are on Mac OS X El Capitan, version 10.11.2.

(I know @jkaving had very similar setup to me, including OS version and webstorm version so it would be great to get his feedback too.). Again, thanks so much for taking the time to help out - much appreciated. I am still not convinced that this issue is strictly local, but getting the above confirmation would go a long way to discounting any other possibility.

**Comment by arcseldon** [comment]
@VernonGrant - sorry, to answer your suggestion. In order to upgrade to Webstorm 11.0.2 necessitated a fresh install. the 11.0.3 was a minor patch only requiring a reboot. I have a lot of custom configurations in the areas of Live Templates, External Tools (Vim) and essential plugins, typed definition files etc etc. Now, whilst it may be possible to pick and choose what I export, I'd rather avoid the effort of having to go down this road unless convinced there is no other option. Hope you can understand this sentiment, wasn't asking you for evidence out of distrust of your findings etc. Thanks again.  

Would add that I use Vim Emulator (vimidea plugin), however I have disabled that and run the setup, and still get the affected blue fonts when Solarize (dark or light) is enabled in the editor. I had wondered whether it was picking up some strange settings from .vimrc / .ideavimrc but this is not the case.

**Comment by jkaving** [comment]
Thanks to @aik099 for helping resolve this issue!
What he means with:
> You need to use Solarized Dark (Darkula) color scheme then not just Solarized Dark.

is that there are actually four versions of the Solarized color scheme for the Jetbrains IDEs.
There are only two versions in the source (`Solarized Dark.icls` and `Solarized Light.icls`) but running the `buildjar.sh` script to generate the `settings.jar` file will actually generate two more versions (named `Solarized Dark (Darcula).icls` and `Solarized Light (Darcula).icls`.
<img width="277" alt="screenshot of webstorm 2016-01-24 08-17-03" src="https://cloud.githubusercontent.com/assets/725090/12534996/e1044afe-c272-11e5-93df-3d54526662c1.png">

This is a solution to issue #62 (and #41, #44 and #46). Please read the discussion there.

@arcseldon - Did you install using the `settings.jar` file or did you copy the `.icls` directly files from this repo? In that case the solution is to install using `settings.jar` (or to extract the Darcula versions from it and install them manually).

Here is two screenshots where I use the Darcula L&F and where you can see the difference between the two version of Solarized Dark:

**Solarized Dark**:
<img width="907" alt="screenshot of webstorm 2016-01-24 08-09-02" src="https://cloud.githubusercontent.com/assets/725090/12534980/d745b8a0-c271-11e5-9fa8-2fcb1c4cb981.png">

*Solarized Dark (Darcula)*:
<img width="863" alt="screenshot of webstorm 2016-01-24 08-09-29" src="https://cloud.githubusercontent.com/assets/725090/12534981/dbfb74f2-c271-11e5-8aa4-eda91fcbb6fd.png">

**Comment by VernonGrant** [comment]
:+1:

**Comment by arcseldon** [comment]
@aik099 @jkaving @VernonGrant - between you, think you nailed this issue, thank you very much for your time and patience. No, I had cut to the chase and just manually installed what I saw in front of me... RTFM... 101. Actually, I had originally downloaded from the Solarize main repo, and when that hadn't worked (but had already built up the experience of doing the manual install), quickly proceeded to back out what I thought must be outdated files, and decided to give this project a go instead - and seeing the files right here in front of me, just took what I saw at face value. Is there any reason why you don't place the darcula equivalents alongside the other two?  :wink:   Again, cheers all.

**Comment by arcseldon** [comment]
ps. please close this issue.

**Comment by arcseldon** [comment]
looks awesome!  happy webstorm user, thanks to all for maintaining this project.

**Comment by jkaving** [comment]
Nice to hear that you got it solved!

> Is there any reason why you don't place the darcula equivalents alongside the other two?

The reason is simply to avoid having to maintain multiple versions of the color scheme files. The changes needed to adapt to Darcula are so small that it is easier to do them automatically in the script that is used to generate the JAR file.
For a while now I have been thinking about improving the way the contents of this repo are built and distributed. It would probably be better to use the GitHub "releases" feature and not have the generated JAR file committed together with the source files. A release could then contain all versions of the color scheme files as well as the `settings.jar`-file.
