### ISSUE TITLE
Suggestion: Use Darcula font in Darcula themes

### ISSUE THREAD

**Issue by Kinnonii** [jkaving/intellij-colors-solarized#116]
Hi!
IDEA uses a more legible font in Darcula theme. I think you should use it too!

**Comment by aik099** [comment]
1. Which font you're suggesting?
2. Not sure if it's possible to specify font as part of imported Color Scheme.

**Comment by jkaving** [comment]
At least on Mac OS X it seems as if both the Default scheme and the Darcula scheme specify Menlo as the font:
<img width="928" alt="screenshot_of_intellij_idea" src="https://cloud.githubusercontent.com/assets/725090/12748221/2bed6c5c-c9a9-11e5-9612-7529d2c9393a.png">
<img width="922" alt="screenshot_of_intellij_idea" src="https://cloud.githubusercontent.com/assets/725090/12748231/3c9adb8e-c9a9-11e5-93ec-090a6289c185.png">

And yes, unfortunately the color schemes does specify the font - see https://github.com/jkaving/intellij-colors-solarized#note-about-fonts.

@Kinnonii - Could you provide screenshots of what you mean?

**Comment by Kinnonii** [comment]
@aik099 @jkaving 
In Windows & Linux the font used in Darcula theme by default is `Source Code Pro` and in the light theme is `DejaVu Sans Mono` which is used in the Solarized Dark (Darcula) theme too.

**Comment by jkaving** [comment]
I actually use the `Source Code Pro` font myself.
It might actually be better to specify that in the Solarized color scheme files.

The Solarized color scheme files currently specify the `Menlo` font, which I believe is only included by default in OS X. So I guess the fonts you get on Windows and Linux are default fonts that IntelliJ IDEA uses when the specified font is not available.
It is possible that IntelliJ IDEA uses different default fonts for the Darcula Look&Feel and the Default Look&Feel.

**Comment by Kinnonii** [comment]
@jkaving In fact it's true, it uses differents font by default. Probably is better to set Source Code Pro as the default font as it's shipped by default with the IDE.

**Comment by jkaving** [comment]
> Probably is better to set Source Code Pro as the default font as it's shipped by default with the IDE.

Oh, that's cool - I didn't know that.
It actually seems to have been included since 2012 (see https://github.com/JetBrains/intellij-community/commit/629a6f2cf719e6dffc78431a4b8f1f2fe4c11ed0).

Then it is definitely better to specify that in the color scheme files. I will change it.

**Comment by Kinnonii** [comment]
@jkaving Very cool! Thank you :)

**Comment by jkaving** [comment]
Actually, it seems as if it is no longer necessary to include a font in the color scheme file.
This is probably an effect of the switch to the `.icls` format (see #51 and #53) and the fact that the color schemes now specify a parent scheme that they inherit settings from.

So an even better solution is probably to remove the font information from the Solarized color schemes. You will then get the default font for your OS.
I will need to investigate whether Solarized Dark should specify Darcula as its parent scheme.

**Comment by alexrayu** [comment]
FUI, for me in PHPStorm 2016.1, css color icons do not show when using Darcula with Source Code Pro.
