### ISSUE TITLE
html.erb not showing right ? 

### ISSUE THREAD

**Issue by Erowlin** [jkaving/intellij-colors-solarized#119]
It seems that there is a problem with the solarized + .html.erb files. Here how it looks like on RubyMine 8.0.3 : 
<img width="894" alt="screenshot 2016-02-27 11 18 47" src="https://cloud.githubusercontent.com/assets/1775878/13372460/eeba22ea-dd43-11e5-9286-b359bc681716.png">

I'm not sure that those white lines `<% %>` are properly displayed. 

I don't know if it's the normal color ? Or maybe an installation problem (I did it twice, restarted the IDE and applied Solarized w/ Darcula). 

Thanks

**Comment by jkaving** [comment]
Unfortunately, there seems to be no support for ERB files - so they will use the colors from the default color scheme (which has a light background and therefore clashes with Solarized Dark).

We will need to add support for ERB.

**Comment by jkaving** [comment]
Fixed by @georgemarshall in #128 which was just merged.
