### ISSUE TITLE
HTML Bracket Highlighting barely readable in Solarized Light

### ISSUE THREAD

**Issue by derwok** [jkaving/intellij-colors-solarized#120]
First: Thanks for adapting Solarized to IntelliJ IDEA!

While working with HTML I very often have the problem that while my cursor is running through the code I barely can read the HTML tags... It seems due to bracket highlighting (see image#1), where my cursor is behind(!) the HTML tag. Here I get dark green background with blue font color.
![solarized_html_image1](https://cloud.githubusercontent.com/assets/4393698/13453044/5ef62228-e04d-11e5-8a7a-7af98e5610b3.png)

Its OK, while inside a tag (see image#2) - nice subtle background color!
![solarized html image2](https://cloud.githubusercontent.com/assets/4393698/13453042/5ef53994-e04d-11e5-90d3-2237a0debf3c.png)

When I am in normal code bracket highlighting has the same greenish background color, which is OK, as the green background gets white text color (see image#3).
![solarized html image3](https://cloud.githubusercontent.com/assets/4393698/13453043/5ef519c8-e04d-11e5-93ea-59f0b45f383d.png)

Is there a possibility to get all-bright text color while bracket matching is active with green background?

**Comment by aik099** [comment]
Related Discussions:

* #108
* #110

**Comment by jkaving** [comment]
As @aik099 says, this seems to be the same problem as in #108 and #109.

@derwok - Are you using the latest version of the color scheme files?

**Comment by derwok** [comment]
Thanks for the hint.
Actually - before writing the issue I downloaded the latest "settings.jar".
And I thought I had successfully updated to this version - but seems I was wrong.
I just repeated download and re-installed - and super! New bracket-highlighting is much better
=> Problem solved. Thanks for the hint. My fault.
And thanks again for your great work to bring these colors to IDEA!  ;-)

**Comment by jkaving** [comment]
No problem - glad to hear you got it sorted out !
