### ISSUE TITLE
intellij-colors-solarized not work in Intellij IDEA 15.0.2

### ISSUE THREAD

**Issue by flike** [jkaving/intellij-colors-solarized#121]
I install intellij-colors-solarized in mac os 10.11.4, but it not work. My OS is  in mac os 10.11.4. But my directory has the files

```
/Users/flike/Library/Preferences/IntelliJIdea15/colors
➜  colors  ll
total 1784
-rw-r--r--  1 flike  staff  111160  3 29 16:29 Solarized Dark (Darcula).icls
-rw-r--r--  1 flike  staff  111160  3 29 16:29 Solarized Dark (Darcula).xml
-rw-r--r--  1 flike  staff   16892  3 29 17:55 Solarized Dark..xml
-rw-r--r--  1 flike  staff  110054  3 29 16:29 Solarized Dark.icls
-rw-r--r--  1 flike  staff  110054  3 29 16:29 Solarized Dark.xml
-rw-r--r--  1 flike  staff  109282  3 29 16:29 Solarized Light (Darcula).icls
-rw-r--r--  1 flike  staff  109282  3 29 16:29 Solarized Light (Darcula).xml
-rw-r--r--  1 flike  staff  108176  3 29 16:29 Solarized Light.icls
-rw-r--r--  1 flike  staff  108176  3 29 16:29 Solarized Light.xml
```

and in Intellij IDEA doesn't has the option to choose solarized theme.
![2016-03-30 08 55 37](https://cloud.githubusercontent.com/assets/1825381/14128653/5b31be2c-f655-11e5-8631-119f72ad728f.png)

**Comment by andreasgrimm** [comment]
neither do they seem to work in:

```
WebStorm 2016.1.1
Build #WS-145.597
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```
on Mac OS-X 10.11.4 (15E65)

**Comment by jkaving** [comment]
Have you restarted the IDE after installing the color scheme?

Is there anything written in the log file when installing the color scheme?
For IDEA the log file can be found using `Help -> Show Log in Finder` (I'm not sure if it's the same in WebStorm).

**Comment by jkaving** [comment]
@flike: The third file in your screenshot looks strange.
![screenshot_of_safari](https://cloud.githubusercontent.com/assets/725090/14996311/9b1cecac-1179-11e6-8782-a2891442b905.png)
Does it work better if you remove that file?

**Comment by alexxsun** [comment]
The same here.

log info:

IDE: Android Studio (build #AI-143.2821654, 28 Apr 2016 00:00) 
OS: Windows 10 (10.0, amd64) 
JRE: 1.8.0_71-b15 (Oracle Corporation) 
JVM: 25.71-b15 (Java HotSpot(TM) 64-Bit Server VM) 
ERROR - rationStore.ComponentStoreImpl - Cannot read scheme Solarized Dark.icls 
org.jdom.input.JDOMParseException: Error on line 52: Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.

**Comment by jkaving** [comment]
That error seems weird:

> ERROR - rationStore.ComponentStoreImpl - Cannot read scheme Solarized Dark.icls 
> org.jdom.input.JDOMParseException: Error on line 52: **Attribute name "data-pjax-transient"** associated with an element type "meta" must be followed by the ' = ' character.

I'm not able to find any occurrence of the string "data-pjax-transient" (or even just "transient") in the color scheme file (or in the history of this repo).

@alexxsun - Could you attach your `Solarized Dark.icls` file?

**Comment by alexxsun** [comment]
@jkaving Thanks for your mention. I re-download theses files, and everything works fine.
Thank you very much! Good job, I love it~
Maybe the easy solution for this issues is that:
Download the files again.

Thanks again.

**Comment by bareberry** [comment]
what about the appearence，It is not work in the appearenc
