### ISSUE TITLE
Wrong Parameter Or Argument Colors For Variables

### ISSUE THREAD

**Issue by marioblokand** [jkaving/intellij-colors-solarized#122]
Variables which are arguments or parameters, have wrong colors in PHP. Regular variable declarations are correct (blue). See the picture below for the problem:

![screenshot from 2016-05-03 18-25-28](https://cloud.githubusercontent.com/assets/10871631/14990438/dbb0d91c-115c-11e6-9a54-1e3e2b4d194a.png)

I am using IntelliJ version 2016.1.1

**Comment by aik099** [comment]
Which color is wrong?

Here is how it works:

* blue - variable declared inside the method
* orange - method parameter

**Comment by marioblokand** [comment]
The color of the method parameter is wrong. The color above is the default color if no color was specified (brownish). All old syntax themes have these issues because Jetbrains changed something with the version 15. I also use the material syntax theme for Jetbrains, it had the same issue (thus the same color for method parameters) but was updated recently.

**Comment by aik099** [comment]
Can you please post screenshot of same code with Solarized Dark theme?

**Comment by aik099** [comment]
And to compare screenshots from Solarized Light & Solarized Dark from previous PhpStorm versions where it worked as you expect.

**Comment by jkaving** [comment]
I think we just need to add an element for `PHP_PARAMETER`.
Like [this commit](https://github.com/ChrisRM/material-theme-jetbrains/commit/899fca970887ad76cd217ac9c87957ea694c68d4) for the material theme.

**Comment by jkaving** [comment]
Now I realize that commit 8a50bbe66c5f7d6460672f5dae2fdc45c4d71cbc by @aik099 actually added the `PHP_PARAMETER` - but only for Solarized Dark.
I will add it for Solarized Light as well.

**Comment by marioblokand** [comment]
Wow, thanks for the quick fix!
