### ISSUE TITLE
Adapt for Elixir/Elm Support

### ISSUE THREAD

**Issue by gerred** [jkaving/intellij-colors-solarized#123]
Hi! I'm wanting to adapt to support these two languages officially. I'm happy to submit a PR for this.

Is there an objective approach to this wrt Solarized, or is this more of a "adjust until things look right" approach?

**Comment by jkaving** [comment]
It would be great if you added support for these languages!

The process so far has been to first look at the examples on http://ethanschoonover.com/solarized and try to match them as much as possible. And then, using only the Solarized colors, use the "adjust until things look right" method :-)

There is no overarching principles for which colors to use for which kinds of syntactic elements.

**Comment by bkbooth** [comment]
I'm also after Elm colours, how'd you go with creating them @gerred?
