### ISSUE TITLE
Errors and Commented lines have the same color.

### ISSUE THREAD

**Issue by mchiareli** [jkaving/intellij-colors-solarized#127]
Commented lines and errors has the same colors when editing Java Files, sometimes its a bit confusing.

<img width="879" alt="screen shot 2016-07-05 at 11 58 33" src="https://cloud.githubusercontent.com/assets/66646/16582621/e75ae164-42a7-11e6-8936-079bb317c2c5.png">

**Comment by jkaving** [comment]
The color for comments was changed in commit 0fe2a7faccd04702f15633d134224b9cb1b17597 and there is some discussion about it in issue #67.

Perhaps changing the line comment color to orange (`#cb4b16`) instead would be better.
It stands out almost as much as the red, but is different from it:

![screenshot of intellij idea 2016-07-05 13-08-54](https://cloud.githubusercontent.com/assets/725090/16582821/c7f37c0a-42b1-11e6-9124-3c6d0af98cd9.png)

Orange seems to be mainly used for numbers.

**Comment by CreamyCookie** [comment]
I'd be in favor of that while also changing the colors to red.

**Comment by aik099** [comment]
@jkaving , what effect change made in above commit will have on comment color in PHP files? It doesn't make sense to change grey comment color into orange one.

**Comment by jkaving** [comment]
@aik099 There seems to be color specifications for the comments of both PHP, JS and CSS, and these haven't been removed, so the colors for those languages shouldn't be affected.

I only removed the comment color specifications for the languages where they where the same as  "Language Defaults" (at least, that was my intention).

**Comment by aik099** [comment]
Thanks.

Actually I was very surprised, when I saw red being used as comment color in Java. I though grey is more or less cross-language standard color for comments.

**Comment by jkaving** [comment]
Yes, the red used for Javadoc in the official Solarized feels a bit too visible.
But as discussed in #67 there are some good arguments for using red (or orange now) for line comments that should usually stand out more.
