### ISSUE TITLE
Modified files are in dark blue against black

### ISSUE THREAD

**Issue by asafm** [jkaving/intellij-colors-solarized#129]
Hi,
After importing lastest settings.jar I see the on the projects view, the modified files are in dark blue in the Solarized Dark.

Any idea why?

![image](https://cloud.githubusercontent.com/assets/989425/17505070/1cafe9a2-5e07-11e6-9fa1-d56cf3938c94.png)

**Comment by jkaving** [comment]
Could you try using the Darcula version of the Solarized Dark theme?
See my comment at https://github.com/jkaving/intellij-colors-solarized/issues/115#issuecomment-174262756 and the issues linked from it.
