### ISSUE TITLE
Some versions are in the releases section on GitHub but only from 2011

### ISSUE THREAD

**Issue by hollasch** [jkaving/intellij-colors-solarized#133]
It would be handy to be able to grab versions from the [releases section](https://github.com/jkaving/intellij-colors-solarized/releases) for this project. If not, then perhaps it's time to retire the releases altogether.

**Comment by jkaving** [comment]
This has now (finally) been fixed.
The old tags have been removed and I have added a workflow that automatically generates the `settings.jar` file, and creates a release with it, when a tag is pushed.
