### ISSUE TITLE
Extention function call highlighting

### ISSUE THREAD

**Issue by elect86** [jkaving/intellij-colors-solarized#134]
Kotlin 1.1 introduced this

![pasted image at 2016_10_19 08_11 pm](https://cloud.githubusercontent.com/assets/5020626/19554165/a99ed8e4-96b7-11e6-8c19-202b78fc69ca.png)

I guess it'd be cool to integrate in the theme..

**Comment by johankaving** [comment]
I'm not familiar with Kotlin - but is this the setting that you suggest changing?
![screenshot_of_intellij_idea](https://cloud.githubusercontent.com/assets/22770463/19556218/6283885c-96c0-11e6-89f0-297a78f9f0ab.png)

It doesn't seem like the default color themes in IntellijJ IDEA assigns any style to these extension function calls, but for some reason (that I haven't figured out) they seem to be italicized.

Do you suggest using any specific color for them?

**Comment by jkaving** [comment]
I'm not familiar with Kotlin - but is this the setting that you suggest changing?

![screenshot_of_intellij_idea](https://cloud.githubusercontent.com/assets/725090/19556488/a6098026-96c1-11e6-92fc-e35b567046c3.png)

It doesn't seem like the default color themes in IntellijJ IDEA assigns any style to these extension function calls, but for some reason (that I haven't figured out) they seem to be italicized.

Do you suggest using any specific color for them?

**Comment by elect86** [comment]
yep, that is

Not in particular, I'd just like them to have a different color  :simple_smile:

**Comment by soshial** [comment]
I think this should be closed. Extension functions are italicized, because those are essentially static functions.
I addressed these issues in this issue: #179.

**Comment by jkaving** [comment]
Static function calls are now italicized, as suggested by @soshial
