### ISSUE TITLE
Kotlin constants

### ISSUE THREAD

**Issue by elect86** [jkaving/intellij-colors-solarized#135]
The highlighting on constants in Kotlin is not always working

`IVRSystem_Version` for example got it, but all the others didn't

![image](http://i.imgur.com/mwBwigm.png)

**Comment by jkaving** [comment]
That's strange.

In the properties I don't see any setting for Kotlin constants:
![screenshot of intellij idea 2016-11-08 09-07-51](https://cloud.githubusercontent.com/assets/725090/20091415/ef0ca5ac-a592-11e6-9cba-70fa04783bea.png)

So I don't understand why `IVRSystem_Version` is coloured differently.

**Comment by elect86** [comment]
Intellij bug probably?

**Comment by jkaving** [comment]
Yes, probably.
Doesn't seem to be something that can be fixed in the color scheme.

**Comment by elect86** [comment]
Ok
