### ISSUE TITLE
Syntax highlighting not working for subpackages

### ISSUE THREAD

**Issue by clebio** [jkaving/intellij-colors-solarized#137]
I've been using this repo with great success on personal projects for a little while. However, I just started working with a company's larger codebase where they have multiple sub-packages in their main repo. The syntax highlighting wasn't working for these subpackages, but when I add one specific subdirectory as a separate project in IntelliJ, it highlights everything just fine.

For example, imagine the Scala project's single Git repo is structured thus:
```
README.md
packageA/
  src/
    main/
      scala/
        AFile.scala
packageB/
  src/
    main/
      scala/
        BFile.scala
```

If I add the base of the repo as a project, nothing gets highlighted correctly (mostly greys). But if I create a new IntelliJ project at the `packageA/` path, then `AFile.scala` is highlight correctly. I don't know anything about IntelliJ settings configs -- is this even managed by your solarized configs, or just IntelliJ itself?

**Comment by clebio** [comment]
Oh, well this is what I need to be doing. I'm pretty new to IntelliJ, so please forgive me if this should be obvious.
https://www.jetbrains.com/help/idea/2016.2/configuring-content-roots.html#d2032217e186

**Comment by jkaving** [comment]
I'm glad you seem to have found the solution.
It sounds like it was a problem with IntelliJ IDEA not detecting the files as source files, and therefore not using any syntax highlighting at all.
