### ISSUE TITLE
Highlighting of method name

### ISSUE THREAD

**Issue by soshial** [jkaving/intellij-colors-solarized#139]
This is really bad, guys :(

![screen shot 2017-01-19 at 10 30 39](https://cloud.githubusercontent.com/assets/100644/22099475/2ff2ef98-de34-11e6-9016-3fe8d939292c.png)

**Comment by dreambottle** [comment]
Just to clarify: this happens in a Darcula-inherited version of the theme.

**Comment by johankaving** [comment]
@dreambottle Thanks for clarifying that - I didn't think to check that version.

I will look into fixing it.

**Comment by jkaving** [comment]
@dreambottle Thanks for clarifying that - I didn't think to check that version.

I will look into fixing it.
