### ISSUE TITLE
Script doesn't generate the darcula inheritance in darcula schemes.

### ISSUE THREAD

**Issue by dreambottle** [jkaving/intellij-colors-solarized#141]
I managed to fix this by replacing
```sed -i'.orig' -e '/<scheme\>/ s/\<\(parent_scheme\)="[^"]*"/\1="Darcula"/' "${2}"```
With
```
  sed -i'.orig' -e '/\(parent_scheme\)="[^"]*"/\1="Darcula"/' "${2}"
```
But I'm too lazy to make a fork and a PR. Could you fix this please. :)
Thanks!

**Comment by jkaving** [comment]
Yep, fixing this - thanks.
Setting the parent scheme was actually added recently in PR #138, but it doesn't seem to work right.

But I need to add an `s` for the sed command in your version:
```
sed -i'.orig' -e 's/\(parent_scheme\)="[^"]*"/\1="Darcula"/' "${2}"
```

Setting the parent scheme to Darcula seems to be the cause of issue #139, so I'm trying to fix this as well.
