### ISSUE TITLE
PhpStorm 2017.1.1 wrong class method color

### ISSUE THREAD

**Issue by aik099** [jkaving/intellij-colors-solarized#145]
![2017-04-07_1046](https://cloud.githubusercontent.com/assets/1277526/24790717/1020497a-1b80-11e7-8fd4-a147a47a9c5c.png)

The class method color in color scheme preview is shown as grey (correct), but actually in the editor it's shown as yellow.

It was working before (I had another copy of Solarized Dark theme), but in my copy inline parameter type hints are shown incorrectly and that's why I went to try latest version of theme.

**Comment by aik099** [comment]
After some clicking in color scheme editor I've found out that method name in class is detected as `Identifiers > Default`, but in editor it works as `Functions and Methods` declaration, which indeed is of orange color.

Now I guess it's time to ask if this was an intended change, because now my PHP class looks like a rainbow with all method names in orange.

**Comment by jkaving** [comment]
We seem to have discussed this quite a bit in issue #58 :-)
See my [comment here](https://github.com/jkaving/intellij-colors-solarized/issues/58#issuecomment-166431312).

**Comment by aik099** [comment]
Ha-ha. So I was initiator of this change, but I wasn't upgrading to new color scheme version for 1.5 year to see that change was actually made 😄 

I guess then this and discussion you've mentioned can be closed.
