### ISSUE TITLE
PhpStorm 2017.1.1 wrong concatenated string color with template language disabled

### ISSUE THREAD

**Issue by aik099** [jkaving/intellij-colors-solarized#146]
With `Editor > Color & Fonts > Language Defaults > Template Language` (used to highlight SQL inside strings) enabled I have nasty background (as on current line) for each concatenated string:

![2017-04-07_1114](https://cloud.githubusercontent.com/assets/1277526/24791620/86a244c4-1b83-11e7-8784-00b0d89deb64.png)

When I disable it however the string color is changed from correct to default identifier color (not related to fact, that function call is concatenated; same thing happens with 2 strings as well):

![2017-04-07_1117](https://cloud.githubusercontent.com/assets/1277526/24791701/d66e61ae-1b83-11e7-82e2-6f9b515d22d6.png)

Works correctly in `Default` theme with both `Template Language` enabled/disabled.

**Comment by aik099** [comment]
Turned out to be a bug in PhpStorm 2017.1.1 that was fixed in PhpStorm 2017.1.2 (see https://blog.jetbrains.com/phpstorm/2017/04/phpstorm-2017-1-2-is-out/).

**Comment by jkaving** [comment]
Ok, great!
