### ISSUE TITLE
PhpStorm 2017.1.1 multiple color elements are shown in blue now

### ISSUE THREAD

**Issue by aik099** [jkaving/intellij-colors-solarized#147]
Before:
![2017-04-07_1605](https://cloud.githubusercontent.com/assets/1277526/24801252/1439332e-1bac-11e7-8484-5e57f33339cf.png)

After:
![2017-04-07_1604](https://cloud.githubusercontent.com/assets/1277526/24801254/19d80d5a-1bac-11e7-89be-09a4a17273c3.png)

Not sure if the change was intended or just a bug in PhpStorm 2017.1.1, but having both property name and braces in blue makes array key access constructs less readable.

**Comment by jkaving** [comment]
This change was intended - and was done in pull request #125 (with a lot of discussion in pull request #124).
The colors for brackets, braces and parentheses was removed for the different languages, so it should be easy to change them everywhere by changing the Language Default setting.

**Comment by aik099** [comment]
> This change was intended - and was done in pull request #125 (with a lot of discussion in pull request #124).

I see. And the class property blue color is part of #58 change.

> The colors for brackets, braces and parentheses was removed for the different languages, so it should be easy to change them everywhere by changing the Language Default setting.

Yes, but then language default for braces (`[` and `]`) should be set to red, because it was set to inherited in Java/PHP.
