### ISSUE TITLE
Make Kotlin theme to be more like java

### ISSUE THREAD

**Issue by turbanoff** [jkaving/intellij-colors-solarized#148]
Hello.
I use solarized light color scheme.
Currently I'm working on project with both languages: java and kotlin. And it's really hard to read code in kotlin after reading java code.
It has too many gray symbols, too _blue_ keywords.
It would be nice to have kotlin highlighting **almost** like java: same colors - same meaning.

**Comment by johankaving** [comment]
I have never used Kotlin myself, so I don't feel particularly suited to fix this.
But I think it sounds reasonable that Kotlin should look similar to Java so pull requests for improving this would be very much appreciated.

**Comment by jkaving** [comment]
I have never used Kotlin myself, so I don't feel particularly suited to fix this.
But I think it sounds reasonable that Kotlin should look similar to Java so pull requests for improving this would be very much appreciated.
