### ISSUE TITLE
colors of solarized blend in with background colors

### ISSUE THREAD

**Issue by Jossnaz** [jkaving/intellij-colors-solarized#149]
this is in intellij 16.3 and phpstorm

i was looking at the http://ethanschoonover.com/solarized theme for coding. I wanted to switch from bright to dark. Why? because I saw a video with someone using the dark theme with nice colors. I liked more colorful, so I wanted to switch. I love the colorized colors... but things are hard to read. Quite the opposite of what was promised...

compare:

```
$user
->fresh()
$stripe_email
```
in intellij bright, I think it is always quite easy to read those. In solarized, the fonts do not look sharp and seem to blend in with the background.

once it is very easy to read, under solarized it is quite ugly to read

what causes this?

intellij standard easy to read IMHO: 
![image](https://cloud.githubusercontent.com/assets/2072058/26757948/c773370a-4893-11e7-8d65-1e82607ffdac.png)

Solarized, things blend in, for example $user. $donor is an example that does NOT blend in:

enter image description here
![image](https://cloud.githubusercontent.com/assets/2072058/26757947/c04df6b8-4893-11e7-9d69-502dde1bded3.png)

zoomed in: 

![image](https://cloud.githubusercontent.com/assets/2072058/26757943/aecf5d14-4893-11e7-91bb-cd9ff0ecc859.png)

![image](https://cloud.githubusercontent.com/assets/2072058/26757945/b501e2f6-4893-11e7-8863-12e32aba89aa.png)

**Comment by aik099** [comment]
The only notable difference, that I've spotted is `$user` variable colored in orange. Is that what's you're concerned about?

It is because function/method parameter color is set to orange. You can override this in theme settings if you'd like. This way it's easier to spot accidental replace of function/method parameter value.

**Comment by Jossnaz** [comment]
hi @aik099
first of all i love the solorized theme, dont get me wrong.


to your question:
the color is orange yes, but not only that.
look in the zoomed in version.

in my opinion clearly `$user` in intellij white and `->fresh` are both a lot better readable than the version of solarized. There is just no doubt about it for me. An example where this is not the case is $donor
$donor is equally well readable in intellij white and solarized.

so yes, the colors must just be poorly chosen or this is an effect nobody has noticed before me? or people just use bigger font-size? (i use 10px). Or is there a different explanation? it seems that some letters, when getting thinner, depending on their color, start blending in more or less with the background color. Look at the u of `$user` look at the right side of that u. The intellij white gets a brighter red, still very good to read, the solarized dark gets half dark. This pattern follows through all those letters. The e in `$user` in solarized looks as if it has some black spots in it. This is the case as well in intellij white, just a lot less notable. Maybe because the colors are not as close as the orange and background?

now of course I can change the color myself of the texts and/or the background color

but just wanted you guys know

maybe you knew this before as a common issue. Or i use a bad font? its mono spaced deja vu

**Comment by aik099** [comment]
I'm using Menlo font of 13px size with 1.2 line spacing with anti-aliasing enabled. Looks good.

**Comment by johankaving** [comment]
In part I think that what you are seeing is actually something that the Solarized color scheme was designed to do - that is, have a lower contrast.
This text is from the [main Solarized page](http://ethanschoonover.com/solarized):

> **1. Selective contrast**
> On a sunny summer day I love to read a book outside. Not right in the sun; that’s too bright. I’ll hunt for a shady spot under a tree. The shaded paper contrasts with the crisp text nicely. If you were to actually measure the contrast between the two, you’d find it is much lower than black text on a white background (or white on black) on your display device of choice. Black text on white from a computer display is akin to reading a book in direct sunlight and tires the eye.
> 
> Solarized reduces brightness contrast but, unlike many low contrast colorschemes, retains contrasting hues (based on colorwheel relations) for syntax highlighting readability.

But in your zoomed-in screenshot I agree that there seems to a problem with the characters and the anti-aliasing making them look to fuzzy.
I guess this effect is related to both the font-size as well as the screen resolution, so perhaps increasing the font-size might help.

**Comment by jkaving** [comment]
In part I think that what you are seeing is actually something that the Solarized color scheme was designed to do - that is, have a lower contrast.
This text is from the [main Solarized page](http://ethanschoonover.com/solarized):

> **1. Selective contrast**
> On a sunny summer day I love to read a book outside. Not right in the sun; that’s too bright. I’ll hunt for a shady spot under a tree. The shaded paper contrasts with the crisp text nicely. If you were to actually measure the contrast between the two, you’d find it is much lower than black text on a white background (or white on black) on your display device of choice. Black text on white from a computer display is akin to reading a book in direct sunlight and tires the eye.
> 
> Solarized reduces brightness contrast but, unlike many low contrast colorschemes, retains contrasting hues (based on colorwheel relations) for syntax highlighting readability.

But in your zoomed-in screenshot I agree that there seems to a problem with the characters and the anti-aliasing making them look to fuzzy.
I guess this effect is related to both the font-size as well as the screen resolution, so perhaps increasing the font-size might help.

**Comment by Jossnaz** [comment]
the thing is I noted is that this effect does not apply with all colors. So I started chaning font colors to brighter colors and am ok now

screen resolution -> do you think a higher res screen would yield better results? i have only 1920x1080

maybe retina displays would improve that effect?

**Comment by jkaving** [comment]
A retina display definitely seems to help.
Here are two screenshots of the orange color where I changed my font to 10 pt Menlo.

The first one is taken on my MacBook Pro 15" with retina screen:
<img width="288" alt="screenshot of intellij idea 2017-06-07 10-07-09" src="https://user-images.githubusercontent.com/725090/26868367-171f3524-4b69-11e7-908e-a41d8791a970.png">

And this one is on my external Philips 272S4L, a 27" screen with 2560x1440 resolution:
<img width="284" alt="screenshot of intellij idea 2017-06-07 10-14-01" src="https://user-images.githubusercontent.com/725090/26868674-2382b312-4b6a-11e7-88e8-3022bcc3496a.png">
