### ISSUE TITLE
Breadcrumbs lost colors after PhpStorm 2017.2 update

### ISSUE THREAD

**Issue by aik099** [jkaving/intellij-colors-solarized#153]
Apparently new styling entity was introduced in PhpStorm 2017.2 update called `Breadcrumbs`:

![2017-07-20_1601](https://user-images.githubusercontent.com/1277526/28418555-c7af7c24-6d64-11e7-92da-1574628d5508.png)

To style:

1. open settings dialog
2. go to `Editor > Color Scheme > General` section (on the left)
3. go to `Editor > Breadcrumbs` (on the right)

Unfortunately defaults makes them totally unreadable.

It seems that for HTML files foreground color (text color) is picked automatically:

![2017-07-20_1628](https://user-images.githubusercontent.com/1277526/28419739-a97e6c8e-6d68-11e7-9da5-fc99a54f75e8.png)

but still I think, that:

* font size could be increased
* maybe make it bolder

**Comment by aik099** [comment]
I've tried changing foreground color for `Editor > Breadcrumbs > Default` element to `839496` and it's much better now:

![2017-07-20_1634](https://user-images.githubusercontent.com/1277526/28420000-6cb34f3a-6d69-11e7-9b07-4f38ea8fd358.png)

Still it would be better if we can increase font size.

**Comment by aik099** [comment]
I've also posted issue to PhpStorm about font size just in case: https://youtrack.jetbrains.com/issue/IDEA-176301

**Comment by jkaving** [comment]
Thanks for noticing and reporting this.

I have fixed it, but in addition to changing the foreground color I also changed the background colors to use Solarized ones.

I hope it looks ok now.
