### ISSUE TITLE
Color issue on Python "self " 

### ISSUE THREAD

**Issue by emmanuel-eraam** [jkaving/intellij-colors-solarized#156]
The actual self color is grey which makes it hard to distinguish from the rest. 
I would gently suggest #b58900 in Italic as in Spyder. 
many thx!

**Comment by soshial** [comment]
Should have some color, I agree. But it shouldn't be italic, as in original IDE color scheme it is not italic:

![Screenshot 2020-04-03 at 09 54 57](https://user-images.githubusercontent.com/100644/78332764-54b3d200-7591-11ea-9146-ad8e98301801.png)
![Screenshot 2020-04-03 at 09 55 29](https://user-images.githubusercontent.com/100644/78332765-567d9580-7591-11ea-9cbc-c9fa22a5fc80.png)

**Comment by jkaving** [comment]
Perhaps something like this:

![Screenshot of IntelliJ IDEA (2024-01-04, 23-25-20)](https://github.com/jkaving/intellij-colors-solarized/assets/725090/b6f4f0ea-e694-4729-8c43-85584eed952c)

It's similar to the default IntelliJ scheme, in that it is a slightly more muted version of the blue color used for e.g. function definitions.
