### ISSUE TITLE
Make static methods italic

### ISSUE THREAD

**Issue by turbanoff** [jkaving/intellij-colors-solarized#157]
TIL by default IntelliJ shows static methods with _italic_ font.
![image](https://user-images.githubusercontent.com/741251/30060415-efeea6e0-924b-11e7-8428-a8c2a07faac0.png)
I find it's useful to see that when method is static or not.
I suggest to make it italic in solarized theme too.

**Comment by soshial** [comment]
Yes, this is definitely a bug with static methods.

Also, some static variables also have this bug, if the are assigned another value (variable `laksa`):

1.  CORRECT, Default theme: ![screen shot 2017-11-02 at 13 20 04](https://user-images.githubusercontent.com/100644/32323475-cbff8026-bfd0-11e7-8539-8946e25e1731.png)
2. CORRECT, solarized theme:
![screen shot 2017-11-02 at 13 20 53](https://user-images.githubusercontent.com/100644/32323476-cc1e0212-bfd0-11e7-839b-bedfd4f63823.png)
3. **BUG**, solarized theme (_italic_ suddenly disappeared):
![screen shot 2017-11-02 at 13 20 42](https://user-images.githubusercontent.com/100644/32323474-cbe1b67c-bfd0-11e7-81fa-bee653a8625d.png)

**Comment by aik099** [comment]
@soshial , bug where, in this project (theme) or the IntelliJ IDEA?

If something is italic in default theme, but not this theme, then it's not a bug in theme.

If something is set italic in theme, but it doesn't work, then bug is on IntelliJ IDEA side.

**Comment by soshial** [comment]
Sveiks :) Well, I thought, that if something was italic in default theme, but not in this theme, then IT IS a bug in solarized theme.

**Comment by aik099** [comment]
Some time ago I also thought like that, but on many occasions since then I've seen that decisions made during this theme development do not always need to be mapped into default theme of the IDE.

As for `italic for static` I vote :-1: because that would mean `$this->assertEquals(...)` would be in italic because PHPUnit assertion methods are defined as static.

**Comment by soshial** [comment]
First, what is so wrong to be italic? In all JetBrains products static methods are italic, including PHP:
![image](https://user-images.githubusercontent.com/100644/32669237-79d2ea94-c648-11e7-8aa7-a524bd453658.png)
Second, static methods in PHP should be used with `::`, i.e. `self::assertThat()`.

**Comment by soshial** [comment]
I addressed this issue in this pull request: #179.

**Comment by jkaving** [comment]
I've now made a commit that makes the changes suggested in #179.
It seems reasonable to follow the behaviour of the default IntelliJ color schemes when it comes to italics for static fields and methods.
