### ISSUE TITLE
Suggestion: create custom theme for material ui for solarized

### ISSUE THREAD

**Issue by tmeusburger** [jkaving/intellij-colors-solarized#159]
This isn't directly related to this work but would be absolutely amazing if you could create a custom theme for the material UI plugin.  Using this we could get a full solarized theme (including panels and ui elements).  I've tried to utilize their custom theme to get close but am not sure how to adapt some of the solarized colors in a user friendly way.

https://github.com/ChrisRM/material-theme-jetbrains

Thank you for considering this.

**Comment by jkaving** [comment]
This seems like a good idea - but I guess it would need to be done as a pull request in the https://github.com/ChrisRM/material-theme-jetbrains repo.

I see that you created an issue there (ChrisRM/material-theme-jetbrains#471) and that you mentioned having started on a custom theme.
Did you get that uploaded somewhere?
