### ISSUE TITLE
The colors look different from what I see on vim

### ISSUE THREAD

**Issue by s-praveen-kumar** [jkaving/intellij-colors-solarized#162]
I have the same theme on vim and it's been my favorite since long. But this looks so different from that one. The one for vim has good contrast and bright text. This looks little faded compared to that. Is this the way it's supposed to be?

**Comment by aik099** [comment]
What do you mean? The colors used (e.g. for background) look differently on IntelliJ IDEA compared to vim? If so, then can you please show a screenshot and just in case color pick colors in each of the apps to prove that they're indeed different.

**Comment by s-praveen-kumar** [comment]
I'm sorry. It is my bad. I did little experiments. Turns out that it was the font that made things different. On vim I used a bolder font, which made the colors look brighter.

**Comment by s-praveen-kumar** [comment]
And @jkaving Thanks for this wonderful project. Love it.

**Comment by jkaving** [comment]
Nice to hear that you found what the problem was.
