### ISSUE TITLE
Can't import settings.jar in IntelliJ

### ISSUE THREAD

**Issue by stantonk** [jkaving/intellij-colors-solarized#166]
I'm running:

IntelliJ IDEA 2018.1.1 (Ultimate Edition)
Build #IU-181.4445.78, built on April 9, 2018
Licensed to n/a / Kevin Stanton
Subscription is active until December 24, 2018
JRE: 1.8.0_152-release-1136-b27 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

I've tried importing the settings.jar several times and Solarized Light and Dark never show up in settings, I only see Darcula and the defaults.

**Comment by sanderv** [comment]
I've managed to import it like this:
- Go to the Preferences; Editor -> Color scheme
- Click on the settings icon to the right and choose 'Import Scheme' -> 'IntelliJ IDEA color scheme'
From there, select the settings.jar and it should show the Solarized schemes.
