### ISSUE TITLE
Can you add a keyword color for "assert_that" word?

### ISSUE THREAD

**Issue by zaz600** [jkaving/intellij-colors-solarized#168]
Can you add a keyword color for "assert_that" word for Python scheme?
assert_that is using in:
- assertpy https://github.com/ActivisionGameScience/assertpy
- PyHamkrest https://github.com/hamcrest/PyHamcrest

It would be nice if color of "assert_that" pseudo-keyword will be the same as "assert" keyword :)

IntelliJ example
<img width="581" alt="2018-10-20 13 06 19" src="https://user-images.githubusercontent.com/1171520/47254298-6111a100-d469-11e8-9c3a-067dd3dd8829.png">

**Comment by jkaving** [comment]
Unfortunately I don't think that's possible.
`assert` is a Python keyword and the color scheme in IntelliJ IDEA contains a setting for the color of keywords.

`assert_that` is just a function defined in a a library.
To be able to colorize that differently we would need e.g. a way to set a color for text matching a certain RegEx. That's not something that IntelliJ IDEA currently supports in its color scheme system.
