### ISSUE TITLE
Importing fails with Intellij Ultimate 2019.3

### ISSUE THREAD

**Issue by ghost** [jkaving/intellij-colors-solarized#177]
When I try to import the *.icls or the settings.jar file I get an error message:

> Import failed: Solarized Dark.icls is not a valid scheme

and

> Import failed: settings.jar is not a valid scheme. There are no color schemes in the chosen file.

**Comment by jkaving** [comment]
Sorry for the late reply - but importing works fine for me in Intellij IDEA 2023.3.2 Ultimate.
