### ISSUE TITLE
Incorrect background color (white) in commit dialog in PhpStorm 2020.1

### ISSUE THREAD

**Issue by aik099** [jkaving/intellij-colors-solarized#178]
In PhpStorm 2019.3 the textarea of commit dialog, where commit message is written was styled the same was as main editor. This no longer happens in PhpStorm 2020.1.

![PhpStorm2020 1_IncorrectCommitDialogColor](https://user-images.githubusercontent.com/1277526/79449093-44691180-7feb-11ea-9f81-08dc362acc4d.png)

Not sure if new color variables were introduced or support for such thing was removed.

**Comment by jkaving** [comment]
I tested this in PhpStorm 2023.3.2 and it seems to depend on the theme you use.
If I use Solarized Dark together with a dark theme I get this:

![Screenshot of PhpStorm (2024-01-04, 21-53-16)](https://github.com/jkaving/intellij-colors-solarized/assets/725090/91be791b-9460-4182-8777-25cf6ccfdad2)

But if I use Solarized Dark with a light theme (see the light borders on the windows) I get this:

![Screenshot of PhpStorm (2024-01-04, 21-54-24)](https://github.com/jkaving/intellij-colors-solarized/assets/725090/4fa97d77-bd14-44dd-8dae-a7cddbd81abe)

The same thing happens with Solarized Light and a dark theme.

When switching the color scheme that is the opposite of the theme I do get this warning:
![Screenshot 2024-01-04 at 21 57 37](https://github.com/jkaving/intellij-colors-solarized/assets/725090/1a9b319e-13eb-49dc-a279-cb14afd902f9)

I don't think there's much that can be done in the color scheme alone to fix this.

**Comment by aik099** [comment]
I'm now using a combination of https://github.com/4lex4/intellij-platform-solarized IDE theme and color scheme from this repository.

P.S.
The plugin was removed by the author, but you can view it on the https://web.archive.org/web/20220926180039/https://github.com/4lex4/intellij-platform-solarized .
