### ISSUE TITLE
The "Color Scheme deprecation" notification in PhpStorm 2022.2

### ISSUE THREAD

**Issue by aik099** [jkaving/intellij-colors-solarized#180]
After upgrading to the PhpStorm 2022.2 I've started to get a "Color Scheme deprecation" notification on each PhpStorm startup with the following text:

```
You are using the Solarized Dark bundled color scheme which will soon be deleted. Consider enabling the Solarized Dark theme instead

Enable Solarized Dark Theme
```

The `Enable Solarized Dark Theme` text is a link for downloading/installing Solarized Themes IntelliJ plugin (see https://plugins.jetbrains.com/plugin/12784-solarized-themes). That plugin is well made, however, editor colors aren't as detailed as in this project.

I've installed themes via importing the `settings.jar` file from this project.

Any idea? Would PhpStorm drop support for custom themes or is it just incorrectly reporting them as deprecated?

**Comment by gucheen** [comment]
I've tried https://github.com/subtheme-dev/solarized, better than [plugins.jetbrains.com/plugin/12784-solarized-themes](https://plugins.jetbrains.com/plugin/12784-solarized-themes) . However, it still has some problems, code completion popup, for example.

**Comment by aik099** [comment]
@jkaving , ping.

**Comment by aik099** [comment]
> As can be seen from the commit log I haven't updated this repo at all for a few years - it's kind of amazing that it still works as well as it does (I still use it).

I use it every working day as well.

> One of the reasons that I lost interest was the new Theme support that was added, and I didn't have time to convert this to a theme at the time. Others were quicker to create themes and I kind of assumed that those would replace this color scheme.

Right now when installing a theme it also installs a connected editor color scheme. So I guess JetBrains is just advertising themes feature, but not removing editor color schemes feature.

Since it's a deprecation warning, then I guess it all will work till 31 Dec 2022. After that, we'll see what will happen.

**Comment by soshial** [comment]
Is the deprecation warning still in place, @jkaving?

BTW, I saw several Solarized themes for Jetbrains IDE: [1](https://plugins.jetbrains.com/plugin/14920-solarized-theme), [2](https://plugins.jetbrains.com/plugin/12112-solarized-theme).

**Comment by jkaving** [comment]
> Is the deprecation warning still in place, @jkaving?

I didn't get it after adding a space to the end of the color scheme names.

**Comment by jkaving** [comment]
> BTW, I saw several Solarized themes for Jetbrains IDE: [1](https://plugins.jetbrains.com/plugin/14920-solarized-theme), [2](https://plugins.jetbrains.com/plugin/12112-solarized-theme).

Yes, that's what I meant with this in my earlier comment:
> One of the reasons that I lost interest was the new Theme support that was added, and I didn't have time to convert this to a theme at the time. Others were quicker to create themes and I kind of assumed that those would replace this color scheme.

**Comment by aik099** [comment]
> One of the reasons that I lost interest was the new Theme support that was added, and I didn't have time to convert this to a theme at the time. Others were quicker to create themes and I kind of assumed that those would replace this color scheme.

@jkaving , in your theme the choice of colors is better.
