### ISSUE TITLE
Importing fails with Intellij Ultimate 2023.3 EAP Ultimate

### ISSUE THREAD

**Issue by elect86** [jkaving/intellij-colors-solarized#182]
It complains

> Fail to load plugin descriptor from file settings.jar

**Comment by jkaving** [comment]
This repo does not contain a plugin - it's just a color scheme.
So it shouldn't be installed from the Plugins section in Settings, but needs to be imported using the `Manage IDE Settings` -> `Import Settings...` menu item.

![Screenshot of IntelliJ IDEA (2024-01-04, 21-10-04)](https://github.com/jkaving/intellij-colors-solarized/assets/725090/1fdd8d36-eb84-4323-8dca-efeaf33b7f23)

You will then get a dialog like this:

![Screenshot 2024-01-04 at 21 11 43](https://github.com/jkaving/intellij-colors-solarized/assets/725090/d742eeaf-526a-4900-b6de-01a276422fce)
