### ISSUE TITLE
Reflect default IDE color change in this theme too

### ISSUE THREAD

**Issue by aik099** [jkaving/intellij-colors-solarized#58]
In http://blog.jetbrains.com/phpstorm/2013/07/better-readability-with-phpstorms-improved-syntax-coloring/ JetBrains announced, that they reassigned some colors to make code easier to read. Colorset is same, but old elements (e.g. method name) is displayed using different color.

@jkaving, can you please make necessary adjustments.

**Comment by jkaving** [comment]
I have now committed a change that makes PHP instance fields blue (as suggested in [your comment here](https://github.com/jkaving/intellij-colors-solarized/issues/58#issuecomment-31447500)) and PHP methods and functions yellow (as suggested [here](https://github.com/jkaving/intellij-colors-solarized/issues/58#issuecomment-31448648)).

**Comment by aik099** [comment]
Not sure, that it was a great idea after all. Yes, some colors needs to be but not in this combination.

Here is how it looks now:
<img width="690" alt="after_your_changes" src="https://cloud.githubusercontent.com/assets/1277526/11975317/5e0d6dbe-a964-11e5-8106-0ff7b61a631c.png">

Here is how it looked before:
<img width="630" alt="before_your_changes" src="https://cloud.githubusercontent.com/assets/1277526/11975320/6a24f66c-a964-11e5-9555-fb5699e4e37b.png">

The pink color for property names was awesome (the `Application` word in example). After made changes now they are blue as local variables in the method, which is confusing.

The orange color for method names/calls is too colorful. For example if you see method call on object given as method parameter then (the `$event` in the example), then you see orange variable plus yellow method name.
