### ISSUE TITLE
Java Doc comment color

### ISSUE THREAD

**Issue by nikmartin** [jkaving/intellij-colors-solarized#67]
Currently, JavaDoc comments are the same color as errors:
```
<option name="JAVA_DOC_COMMENT">
      <value>
        <option name="FOREGROUND" value="dc322f" />
      </value>
    </option>
```

I'd like to open a disussion of making these another color in the palette.  Is this a standard color for JavaDoc comments?  They REALLY jump off the screen if you use them a lot, and make actual errors hav a lot less contrast and impact in the editor window.

**Comment by NicolasSiver** [comment]
Don't treat them as errors ;)

Here is example from Vim by color theme author:

![Java doc](http://ethanschoonover.com/solarized/img/screen-java-dark.png)

**Comment by jkaving** [comment]
[This article](https://medium.com/@MrJamesFisher/your-syntax-highlighter-is-wrong-6f83add748c9) has an interesting opinion about syntax highlighting of comments.
Based on that I am actually inclined to got the opposite way than what is suggested in this issue - make the line comments red as well :-)

**Comment by IceMan81** [comment]
@jkaving I agree with @nikmartin that the javadoc color kind of stares down at you, it almost becomes a distraction. While the article is interesting, this red I feel hinders readability of the code. I found that there is an experimental green in the vim color scheme - #719e07, both the greens are good choices.

**Comment by jkaving** [comment]
Here is a screenshot of a part of `java.lang.String` with the comments colored with inspiration form the article mentioned in [my previous comment](https://github.com/jkaving/intellij-colors-solarized/issues/67#issuecomment-70159523):
<img width="678" alt="screenshot of intellij idea 2015-12-21 22-38-38" src="https://cloud.githubusercontent.com/assets/725090/11941979/a11f6b7a-a833-11e5-9aaf-ac54d09f36b9.png">

This makes the Javadoc less obtrusive and makes the line comment with an important note stand out more.
I think I like it - but would be happy to get comments on it.

**Comment by jkaving** [comment]
And the Solarized Dark version:
<img width="651" alt="screenshot of intellij idea 2015-12-21 22-44-37" src="https://cloud.githubusercontent.com/assets/725090/11942078/6e170372-a834-11e5-8861-c472e7d33746.png">

**Comment by IceMan81** [comment]
@jkaving I'm not sure there is a clear cut approach here. How does it feel when you take a look at `java.util.HashMap`. There are large block comments blocks of in-line code comments there.

I do feel there is value in highlighting the inline code comments more than the javadocs for the following reasons:

1. With the current scheme, it is very easy to miss the in-line code comments and they generally have valuable information that developers should pay attention to.
2. Java-docs have a particular structure, so they are noticeable. Having said this, using the light grey for the comments make it too subtle and I feel it looses its place in code.

Just my thoughts...

**Comment by jkaving** [comment]
I agree that there is no clear cut approach.

For Solarized Light I think using green (as suggested by @nikmartin above as well) for Javadoc looks pretty good.
![screenshot of intellij idea 2015-12-22 09-31-09](https://cloud.githubusercontent.com/assets/725090/11951803/43dc44ae-a894-11e5-8986-d18826629e6d.png)

For Solarized Dark, however, I think it sticks out a bit too much.
Here I think using a a grey color is better, but in the image below I have switched to base00 (`#657b83`) instead, which is a tad lighter than base01 used in the previous image:
![screenshot of intellij idea](https://cloud.githubusercontent.com/assets/725090/11951798/378f28ba-a894-11e5-8b67-452c8c2ba223.png)
(click on this image to view it larger).

Whether block comments should be colored like line comments or like Javadoc is not obvious, and your example (`java.util.HashMap`) shows that making them red can be a problem sometimes.
However, there is a quite clear semantic difference between Javadoc comments and other comments in Java code. No such difference exists between line comments and block comments.
Therefore it seems most reasonable to color Javadoc in one color and line/block comments in another.

**Comment by IceMan81** [comment]
@jkaving I agree, for Solarized Dark the green sticks out too much. I like the combinations you have proposed : green & red for Solarized Light and grey and red for Solarized Dark. 

>No such difference exists between line comments and block comments.
>Therefore it seems most reasonable to color Javadoc in one color and line/block comments in >another.another.
I agree.

**Comment by IceMan81** [comment]
@jkaving It looks like Intellij makes a distinction between block comments & line comments. If you look in Colors & Fonts -> Language Defaults, you will see separate Block comment & Line comment settings.

**Comment by jkaving** [comment]
@IceMan81
Yes, IntelliJ does distinguish between block comments and line comments.

Do you suggest that they should be colored differently?

Thanks, by the way, for commenting and thereby reminding me about this issue. I should at least make the changes suggested earlier.

**Comment by IceMan81** [comment]
@jkaving from looking at some of the usages of block comments vs line comments within the Java source code as a reference, I feel that block comments could have the same color as Java docs. Line comments in red would highlight small but important comments made by the developer as well commented out code, that really should eventually disappear from the source code. 
That's my thinking right now, this could change after I use this color combination for sometime.  The other day I was looking at some of my own code which had a lot of red in it (mostly because of commented out code) and it got me thinking about this.

**Comment by jkaving** [comment]
@IceMan81 I agree with you, and I have just committed a change according to what we have discussed above.
Line comments are now red, while Javadoc and block comments are green (in Solarized Light) or grey (in Solarized Dark).
