### ISSUE TITLE
Intellij 13, error importing settings.jar

### ISSUE THREAD

**Issue by blackat** [jkaving/intellij-colors-solarized#75]
Hi,
I have downloaded the settings.jar file and I have tried to import it in Intellij 13.1.4 but I get an error preventing the import.

Error reading file '/settings.jar' 
There was error in opening zip file

Has the settings.jar file been generated for a specific version of Intellij?

**Comment by fglez-tsl** [comment]
I am experiencing the same problems with IntelliJ 13.1.6

If I try with the icls files I get the following messages

Cannot read scheme Solarized Dark.icls  from '$ROOT_CONFIG$/colors': Error on line 31: Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.

Cannot read scheme Solarized Light.icls  from '$ROOT_CONFIG$/colors': Error on line 31: Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.
