### ISSUE TITLE
Inline literals color in RST files

### ISSUE THREAD

**Issue by aik099** [jkaving/intellij-colors-solarized#76]
The `inline literals` in the RST files (reStructuredText) become invisible when I place cursor on a line, where they are used.

Before:
![solarized_rst_notcurrentline](https://cloud.githubusercontent.com/assets/1277526/4095951/3a25fed0-2fbb-11e4-8aa4-e09e31c8db4e.png)
 
After:
![solarized_rst_currentline](https://cloud.githubusercontent.com/assets/1277526/4095954/45d07576-2fbb-11e4-8ac5-4ce20980b1ed.png)

Look at 3rd line and see, that all 3 `inline literals`, that were wrapped with \`\` became invisible. This fact makes it unrealistic to edit their values.

**Comment by aik099** [comment]
@jkaving , ping.

**Comment by jkaving** [comment]
Thanks for the reminder :-)

I have tried to make it better - let me know what you think.

**Solarized Light**
Cursor _not_ on the line:
![screenshot of pycharm 2016-06-20 09-25-56](https://cloud.githubusercontent.com/assets/725090/16186172/55db8df4-36c9-11e6-8fe8-5524c37f799c.png)
Cursor on the line:
![screenshot of pycharm 2016-06-20 09-26-11](https://cloud.githubusercontent.com/assets/725090/16186177/5ca6d7e2-36c9-11e6-805c-c1759e497149.png)

**Solarized Dark**
Cursor _not_ on the line:
![screenshot of pycharm 2016-06-20 09-26-46](https://cloud.githubusercontent.com/assets/725090/16186219/96a38ad0-36c9-11e6-95c7-3ab9873d8ba2.png)
Cursor on the line:
![screenshot of pycharm 2016-06-20 09-27-20](https://cloud.githubusercontent.com/assets/725090/16186235/a61fe616-36c9-11e6-8ec2-e0309076749c.png)

**Comment by aik099** [comment]
* for Solarized Light all looks good
* for Solarized Dark foreground (text) color is too bright

**Comment by jkaving** [comment]
It is a bit tricky trying to find a good combination while keeping to only the Solarized colors.
Would you prefer one of these?

![screenshot of pycharm 2016-06-20 09-47-15](https://cloud.githubusercontent.com/assets/725090/16186708/501fcada-36cc-11e6-9ce6-c5c568305c49.png)
![screenshot of pycharm 2016-06-20 09-47-49](https://cloud.githubusercontent.com/assets/725090/16186710/545277ba-36cc-11e6-910c-42933a23172e.png)

I would prefer the top one, but perhaps the background is too subtle?

**Comment by aik099** [comment]
Top one looks good.
