### ISSUE TITLE
Javascript is incorrect.

### ISSUE THREAD

**Issue by nackjicholson** [jkaving/intellij-colors-solarized#81]
The syntax highlighting for javascript is not even close to what's listed on the Solarized home page.

Correct:
![img](http://ethanschoonover.com/solarized/img/screen-javascript-dark.png)

Actual:

![screen shot 2014-11-04 at 8 49 30 am](https://cloud.githubusercontent.com/assets/365247/4903702/a5716254-6442-11e4-851b-5f062214dc86.png)

**Comment by NicolasSiver** [comment]
Closest that I have created:

![Idea JS Colors](http://i.imgur.com/UXDjJuK.png)

Comments:

- Idea can't split keywords, so `this` and `return` have the same color;
- Idea treats RegExps better, so it will be mistake to color them just as strings

@jkaving if you are happy with a result, I could create pull request for JS color scheme.

**Comment by jkaving** [comment]
@NicolasSiver Nice! It's much closer to the official Solarized screenshot.
It would be create if you could create a pull request for it.

**Comment by NicolasSiver** [comment]
@jkaving could you share info, what does IDE add to `.icls` files?
Because I'm developing color schemes by help of IDE (Idea or WebStorm) and as a result diff on 700+ lines. Thanks.

**Comment by jkaving** [comment]
The first thing is that the font is unfortunately a part of the color scheme, so Idea will change the
`<option name="EDITOR_FONT_NAME" value="Menlo" />`
line in the beginning of the file.

It will also add elements for lots of things that doesn't have any effect.
Either complete elements like this:

    <option name="ABSTRACT_CLASS_NAME_ATTRIBUTES">
      <value>
        <option name="EFFECT_TYPE" value="0" />
      </value>
    </option>

... or lines like this (that are added to almost all elements, and from what I can tell only says that there should be no text effect):

    <option name="EFFECT_TYPE" value="0" />

I think the easiest way to make changes is to do them in the "Preferences" dialog in Idea, then copy the color scheme file to your intellij-colors-solarized repository and before committing revert all irrelevant changes using something like [Atlasssian's SourceTree](http://www.sourcetreeapp.com) or Idea itself.

**Comment by NicolasSiver** [comment]
Oh, It takes some time to remove IDE changes to color theme.
Propose to don't fight with
 
    <option name="EFFECT_TYPE" value="0" />

;)

**Comment by jkaving** [comment]
Yeah, it might seem unnecessary to remove stuff that IntelliJ adds back automatically.
But keeping the color scheme files, and the changes made in commits, as small as possible makes it easier to see what has been changed in each commit.

It also makes it easier to copy changes from one of the scheme files to the other (as I did with the changes in your pull request #88).

**Comment by NicolasSiver** [comment]
After revisiting what have been changed. IDE just have added for every property single line, so `value` block isn't empty

   <option name="EFFECT_TYPE" value="0" />

For very first commit, it will be huge amount of changes, but for future contributions, it will be the same small readable diff. Because IDE doesn't reformat color scheme.

**Comment by jkaving** [comment]
Yes, that's true.
It would basically be the reverse of 8ac91ea, which I made a year ago.
I honestly don't remember if I had any other reasons for making that change.
