### ISSUE TITLE
Reference hyperlink is blended with 'execution point' background

### ISSUE THREAD

**Issue by alexey-danilov** [jkaving/intellij-colors-solarized#86]
![blended](https://cloud.githubusercontent.com/assets/4075759/5540156/c23d449c-8ad1-11e4-8257-dd287eb2a818.jpg)

The fix that worked for me was setting background color to 354045 (it is outide of solarized palette, but in this case works fine, and plays nicely with Darkula theme), plus disabling the foreground color for text, so that default color is used.

![ok](https://cloud.githubusercontent.com/assets/4075759/5540177/f9afcf6c-8ad1-11e4-9c6f-d1a822b460d7.jpg)

**Comment by jkaving** [comment]
Thanks for noticing this, and for suggesting a fix!
I opted for your second idea - making the background dark enough that the hyperlinks become yellow.
(I feel that it is nice to have the execution point stand out with the blue color).

I made the same change for Solarized Light.
