### ISSUE TITLE
Stripe Mark: write state

### ISSUE THREAD

**Issue by NicolasSiver** [jkaving/intellij-colors-solarized#89]
Propose to change color of  identifier's `write` state on something more notable.

Example, how it looks now:

![Just an example](http://i.imgur.com/WwfJdK7.png)

**Comment by aik099** [comment]
I suppose light blue vertical bars on the left side of gutter area are ones you're talking about?

Look pretty visible to me. Also, if project is under VCS control then on editor left side you should be seeing pretty large bars indicating if it's an addition/change/removal.

**Comment by NicolasSiver** [comment]
I'm talking about stripe mark that is 4-th from the top

**Comment by aik099** [comment]
Pink one you mean? But this color is used to indicate all occurrences of selected code element in other parts of the file.

Looks quite visible to me. Unless you have several of them in a small piece of code, which will render any stripe mark useless.

**Comment by NicolasSiver** [comment]
... Actually all of these light stripes is occurrences. And barely visible pink is `write` (Initialization of variable).

**Comment by aik099** [comment]
Ah, that what you mean by `write`. The write to the variable, not the write to a file, as I thought initially.

In editor such write occurrence is marked as light red and we can't use same color in gutter area because of red color being used for error display.
![phpstorm_solarizeddark_variablereadwrite](https://cloud.githubusercontent.com/assets/1277526/5837569/f64d56d2-a188-11e4-8a0f-16c259aee59c.png)

**Comment by NicolasSiver** [comment]
I'm talking only about stripe marks, and such stripe mark can have any color (from Solarized palette for example), without impact on text background color. 

@jkaving share your opinion ;)

**Comment by jkaving** [comment]
I agree that it could probably be made more notable.

I have tried tweaking the colors a bit and this is how it looks with
Identifier under caret = `RGB#96CCFF`
Identifier under caret (write) = `RGB#FFC8C8`
(I think it's quite ok to use colors outside of the Solarized palette for the stripe marks).

![screenshot of intellij idea 21-01-15 16 46 13](https://cloud.githubusercontent.com/assets/725090/5839295/8af3c75e-a18d-11e4-8c8d-16cd7f927948.png)     ![screenshot of intellij idea 21-01-15 16 46 42](https://cloud.githubusercontent.com/assets/725090/5839301/967dd20e-a18d-11e4-8fcf-4c8270f88345.png)

In the images there is one write access, followed by two read accesses and one TODO comment.

For me this looks a bit better - what do you think?
Do you have other suggestions?

**Comment by aik099** [comment]
I guess I don't have designer eye to see a difference :wink:

**Comment by NicolasSiver** [comment]
@jkaving is it IDE by Jetbrains? How do you have such stripe marks?

**Comment by jkaving** [comment]
@NicolasSiver Yep, it's IntelliJ IDEA 14.0.2 running on Mac OS X Yosemite 10.10.1 on a 15-inch Retina Macbook Pro.

**Comment by NicolasSiver** [comment]
I would give it more color intensity.
From my experience: write-occurence is most important, especially when you try remember or understand code ;)

**Comment by jkaving** [comment]
`RGB#FF82CE` perhaps?

![screenshot of intellij idea 21-01-15 21 46 11](https://cloud.githubusercontent.com/assets/725090/5844788/0136e7f6-a1b7-11e4-93e8-64e1b1c9323f.png)   ![screenshot of intellij idea 21-01-15 21 44 51](https://cloud.githubusercontent.com/assets/725090/5844782/f408c194-a1b6-11e4-9674-2c41fca4886b.png)

To get an idea for what works you probably need to try it yourself - it is hard to tell from a screenshot what works in practice.

**Comment by NicolasSiver** [comment]
Better. In same direction, and from Solarized: #D33682 ?

![Example of solarized](http://i.imgur.com/A9g4FSi.png)

**Comment by jkaving** [comment]
For me that seems almost too dark - but I think it is also a matter of screen calibration and brightness.
It will probably be hard to find a color that pleases everyone :-)

**Comment by NicolasSiver** [comment]
Why dark? It's a native color for Solarized theme, you should love it ;)

**Comment by jkaving** [comment]
:-)
