### ISSUE TITLE
JavaScript variable color change in Solarized Dark

### ISSUE THREAD

**Issue by aik099** [jkaving/intellij-colors-solarized#96]
Before the variables in JavaScript were orange, but now they are white. Was that intentional change?

Before:
![solarizeddark_javascriptvariablesbefore](https://cloud.githubusercontent.com/assets/1277526/6871208/aff7f030-d4a9-11e4-8e48-68cec523c75a.png)

After:
![solarizeddark_javascriptvariablesafter](https://cloud.githubusercontent.com/assets/1277526/6871214/b42ae4f0-d4a9-11e4-995f-d28afe76e237.png)

**Comment by aik099** [comment]
In fact I've just noticed that some other elements also have different color. I guess change was intentional.

**Comment by jkaving** [comment]
Yes, this was intentional - see issue #81.
